(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var $,MemoryGrid;$=window.$,MemoryGrid=require("./memorygrid"),$(document).ready(function(){var r;return r=new MemoryGrid($("#container"))});

},{"./memorygrid":4}],2:[function(require,module,exports){
var $,Card;$=window.$,module.exports=Card=function(){function t(t){var a,i;this.image=t,this._matched=!1,this.$card=$('<div class="memory-card"></div>'),i=$('<div class="front"></div>'),i.css("background-image","url("+this.image+")"),i.appendTo(this.$card),a=$('<div class="back"></div>'),a.appendTo(this.$card)}return t.prototype.tryMatch=function(t){return this._matched=t.image===this.image,t._matched=this._matched},t.prototype.isMatched=function(){return this._matched},t.prototype.hide=function(){return this.$card.removeClass("faceup")},t.prototype.show=function(){return this.$card.addClass("faceup")},t}();

},{}],3:[function(require,module,exports){
var allImages,_;_=window._,allImages=["images/image0.jpg","images/image1.jpg","images/image2.jpg","images/image3.jpg","images/image4.jpg","images/image5.jpg","images/image6.jpg","images/image7.jpg","images/image8.jpg","images/image9.jpg","images/image10.jpg","images/image11.jpg","images/image12.jpg","images/image13.jpg","images/image14.jpg"],module.exports=function(g){return _.sample(allImages,g)};

},{}],4:[function(require,module,exports){
var $,Card,MemoryGrid,getRandomImages,_;$=window.$,_=window._,Card=require("./card"),getRandomImages=require("./getrandomimages"),module.exports=MemoryGrid=function(){function e(e,t,d){var r,s,i,a,l,h,o,c,n,u;for(null==t&&(t=12),null==d&&(d=4),this.$grid=$("<div></div>"),this.$grid.addClass("memory-grid"),this.cards=[],n=getRandomImages(t/2),l=0,o=n.length;o>l;l++)a=n[l],this.cards.push(new Card(a)),this.cards.push(new Card(a));for(this.cards=_.shuffle(this.cards),u=this.cards,i=h=0,c=u.length;c>h;i=++h)s=u[i],i%d===0&&(r=$("<div></div>"),r.appendTo(this.$grid)),s.$card.appendTo(r),s.$card.click($.proxy(this._cardClicked,this,s));this.selected=null,this.$grid.appendTo(e)}return e.prototype._cardClicked=function(e){var t,d,r,s,i;if(null!=this.cardsToClear){for(i=this.cardsToClear,r=0,s=i.length;s>r;r++)t=i[r],t.hide();this.cardsToClear=null}return e.isMatched()||null!=this.selected?!e.isMatched()&&null!=this.selected&&this.selected!==e&&(e.show(),d=e.tryMatch(this.selected),d||(this.cardsToClear=[e,this.selected]),this.selected=null,_.every(this.cards,function(e){return e.isMatched()}))?this._gameCompleted():void 0:(e.show(),this.selected=e)},e.prototype._gameCompleted=function(){return alert("You won!")},e}();

},{"./card":2,"./getrandomimages":3}]},{},[1])